title: Stick of Celery Webcomics
author: soup-bowl
email: code@soupbowl.io
description: >-
  Stick of Celery and Soupbowl Comics
url: "https://webcomics.soupbowl.io"
#permalink: "/comic/:year/:month/:day/:title"

exclude: ['.github', '.vscode', 'README.md', 'LICENSE', 'docker-compose.yml', 'Gemfile.lock', 'Gemfile']

theme: minima
minima:
  date_format: "%-d %B %Y"

sass:
  style: compressed

collections:
  comics:
    output: false

pagination:
  enabled: true
  per_page: 1
  permalink: "/:num/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-feed
