name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '.gitpod.yml'
      - 'LICENSE'
      - 'README.md'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3

      - name: 📦 Compile Site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: 🚛 Publish Site
        uses: cloudflare/pages-action@v1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: webcomics
          directory: _site
          wranglerVersion: '3'
